services:
  - type: web
    name: legal-linguistic-comparator
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn application:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - requirements.txt
        - "**.py"
    disk:
      name: pip-cache
      mountPath: /root/.cache/pip
